apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: authservice
      app.kubernetes.io/name: authservice
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/instance: authservice
        app.kubernetes.io/name: authservice
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: authservice
        ports:
        - containerPort: 10003
          name: grpc
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/authservice
          name: config-secret
          readOnly: true
      volumes:
      - name: config-secret
        secret:
          defaultMode: 420
          secretName: authservice-config