apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 10003
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/instance: authservice
    app.kubernetes.io/name: authservice
